# Generated by Django 3.0.5 on 2021-01-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corosel',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
