# Generated by Django 3.0.5 on 2021-01-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_configurations', '0002_corosel_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corosel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
