# Generated by Django 3.0.1 on 2020-04-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='city',
            new_name='post_code_id',
        ),
    ]
