# Generated by Django 3.0.5 on 2020-05-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200513_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default='2020-05-14'),
            preserve_default=False,
        ),
    ]
