# Generated by Django 3.0.5 on 2020-05-16 19:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_producerimage'),
        ('account', '0004_auto_20200514_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='value',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_discount', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('product_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grp_discount', to='product.ProductGroup')),
            ],
            options={
                'verbose_name': 'User discount',
                'verbose_name_plural': 'User discounts',
            },
        ),
    ]
