# Generated by Django 3.0.5 on 2020-05-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('RSD', 'Dinar'), ('EUR', 'Euro')], default='RSD', max_length=3)),
                ('unit_of_measure', models.CharField(choices=[('M', 'Meter'), ('K', 'Kilogram'), ('P', 'Piece')], default='P', max_length=1)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=30, unique=True)),
                ('link', models.TextField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Product group',
                'verbose_name_plural': 'Product groups',
            },
        ),
        migrations.CreateModel(
            name='ProducerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='producer_img/')),
                ('image_name', models.CharField(blank=True, max_length=30, null=True)),
                ('content_type', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=20, null=True)),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_image', to='product.Producer')),
            ],
            options={
                'verbose_name': 'Producer image',
                'verbose_name_plural': 'Producer images',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=30)),
                ('is_selectable', models.BooleanField(default=False)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_article', to='product.Article')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_feature', to='product_category.Feature')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_img/')),
                ('image_name', models.CharField(blank=True, max_length=30, null=True)),
                ('content_type', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=20, null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.Article')),
            ],
            options={
                'verbose_name': 'Article image',
                'verbose_name_plural': 'Article images',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='producer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_producer', to='product.Producer'),
        ),
        migrations.AddField(
            model_name='article',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_group', to='product.ProductGroup'),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='product_category.SubCategory'),
        ),
    ]
