# Generated by Django 3.0.1 on 2020-04-17 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=30, unique=True)),
                ('link', models.TextField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=30)),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='product.Producer')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('unit_of_measure', models.CharField(choices=[('M', 'Meter'), ('P', 'Piece')], default='P', max_length=1)),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_category.SubCategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProducerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='producer_img/')),
                ('image_name', models.CharField(max_length=30)),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_image', to='product.Producer')),
            ],
            options={
                'verbose_name': 'Article image',
                'verbose_name_plural': 'Article images',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=30)),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_feature', to='product_category.Feature')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_product', to='product.Product')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_img/')),
                ('image_name', models.CharField(max_length=30)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.Article')),
            ],
            options={
                'verbose_name': 'Article image',
                'verbose_name_plural': 'Article images',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='product.Product'),
        ),
        migrations.AddField(
            model_name='article',
            name='program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Program'),
        ),
    ]
