# Generated by Django 3.0.5 on 2020-05-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='product_group',
            new_name='product_group_id',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='is_selectable',
        ),
    ]
