# Generated by Django 3.0.1 on 2020-04-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producerimage',
            options={'verbose_name': 'Producer image', 'verbose_name_plural': 'Producer images'},
        ),
    ]
