# Generated by Django 3.0.5 on 2020-05-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200505_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
