# Generated by Django 3.0.5 on 2020-05-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_article_article_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
