# Generated by Django 3.0.1 on 2020-04-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200418_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='producerimage',
            name='content_type',
        ),
    ]
