# Generated by Django 3.0.1 on 2020-04-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200418_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producerimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
