# Generated by Django 3.0.1 on 2020-04-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200418_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='currency',
            field=models.CharField(choices=[('RSD', 'Dinar'), ('EUR', 'Euro')], default='RSD', max_length=3),
        ),
    ]
