# Generated by Django 3.0.5 on 2020-05-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_producer_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProducerImage',
        ),
    ]
