# Generated by Django 3.0.1 on 2020-04-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_article_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='content_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producerimage',
            name='content_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
