# Generated by Django 3.0.5 on 2020-05-17 02:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_delete_producerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pieces', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_article', to='product.Article')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_email', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
            options={
                'verbose_name': 'Payment item',
                'verbose_name_plural': 'Payment items',
            },
        ),
    ]
