# Generated by Django 3.0.1 on 2020-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200418_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='purpose',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producerimage',
            name='purpose',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
