# Generated by Django 3.0.5 on 2020-05-17 03:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200517_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentorder',
            old_name='payment_item_id',
            new_name='payment_items',
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='article_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='user_discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='method_of_payment',
            field=models.CharField(choices=[('PS', 'Payment slip')], default='PS', max_length=2),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('IN', 'In the processing'), ('RE', 'Rejected'), ('RW', 'Rejected with counter offer'), ('AP', 'Approved'), ('WF', 'Waiting for payment'), ('SS', 'Shipment sent'), ('PD', 'Products delivered')], default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
