# Generated by Django 3.0.1 on 2020-04-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200425_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='article',
            name='article_name',
            field=models.CharField(default='Stedljive sijalice', max_length=80),
            preserve_default=False,
        ),
    ]
