# Generated by Django 3.0.5 on 2020-05-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200517_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentitem',
            name='article_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
