# Generated by Django 3.0.5 on 2020-05-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200517_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='payment_items',
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='payment_order_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to='product.PaymentOrder'),
            preserve_default=False,
        ),
    ]
