# Generated by Django 3.0.5 on 2020-05-17 12:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200517_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentitem',
            name='article_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
