# Generated by Django 3.0.5 on 2020-05-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200518_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentitem',
            name='reject_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
