# Generated by Django 3.0.5 on 2020-05-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_paymentitem_reject_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentitem',
            name='payment_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.PaymentOrder'),
        ),
    ]
