# Generated by Django 3.0.5 on 2020-05-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200523_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
