# Generated by Django 3.0.5 on 2020-05-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200523_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unit_of_measure',
            field=models.CharField(choices=[('M', 'Metar'), ('K', 'Kilogram'), ('P', 'Komada')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('DR', 'U izradi'), ('IN', 'U obradi'), ('RE', 'Odbijeno'), ('RW', 'Odbijeno sa kontra ponudom'), ('WF', 'Čekanje na uplatu'), ('SS', 'Porudzbina poslata'), ('PD', 'Porudzbina isporučena')], default='DR', max_length=2),
        ),
    ]
