# Generated by Django 3.0.5 on 2021-01-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_articlegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlegroup',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
