# Generated by Django 3.0.5 on 2021-01-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_articlegroup_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegroup',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
