# Generated by Django 3.0.5 on 2021-04-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20210130_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrderCommentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OH', 'NA_CEKANJU'), ('IP', 'U_OBRADI'), ('RJ', 'ODBIJENO'), ('MF', 'MODIFIKOVANO'), ('AP', 'ODOBRENO_ZA_SLANJE'), ('SS', 'POSLATO'), ('PR', 'VRACENA'), ('PD', 'ISPORUCENJA')], max_length=2)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payyment order comment',
                'verbose_name_plural': 'Payment order comments',
            },
        ),
        migrations.RemoveField(
            model_name='paymentitem',
            name='reject_comment',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='attribute_notes',
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='article_attributes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='city',
            field=models.CharField(default='Belgrade', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='method_of_payment',
            field=models.CharField(choices=[('PS', 'KUCNA_DOSTAVA')], default='PS', max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('OH', 'NA_CEKANJU'), ('IP', 'U_OBRADI'), ('RJ', 'ODBIJENO'), ('MF', 'MODIFIKOVANO'), ('AP', 'ODOBRENO_ZA_SLANJE'), ('SS', 'POSLATO'), ('PR', 'VRACENA'), ('PD', 'ISPORUCENJA')], default='OH', max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='zip_code',
            field=models.CharField(default=12333, max_length=15),
            preserve_default=False,
        ),
    ]
