# Generated by Django 3.0.5 on 2021-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20210410_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='note',
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='valid',
            field=models.CharField(choices=[('-1', 'FALSE'), ('0', 'NONE'), ('1', 'TRUE')], default='0', max_length=2),
        ),
    ]
