# Generated by Django 3.0.5 on 2021-04-11 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0024_auto_20210411_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentordercommenthistory',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, to_field='email'),
            preserve_default=False,
        ),
    ]
