# Generated by Django 3.0.5 on 2021-04-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20210414_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentitem',
            name='number_of_pieces',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
