# Generated by Django 3.0.5 on 2021-04-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20210415_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'NA_CEKANJU'), (1, 'U_OBRADI'), (2, 'ODBIJENO'), (3, 'MODIFIKOVANO'), (4, 'ODOBRENO_ZA_SLANJE'), (5, 'POSLATO'), (6, 'VRACENA'), (7, 'ISPORUCENJA')], default=0),
        ),
        migrations.AlterField(
            model_name='paymentordercommenthistory',
            name='status',
            field=models.CharField(choices=[(0, 'NA_CEKANJU'), (1, 'U_OBRADI'), (2, 'ODBIJENO'), (3, 'MODIFIKOVANO'), (4, 'ODOBRENO_ZA_SLANJE'), (5, 'POSLATO'), (6, 'VRACENA'), (7, 'ISPORUCENJA')], max_length=2),
        ),
    ]
