# Generated by Django 3.0.5 on 2021-04-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20210416_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='method_of_payment',
            field=models.IntegerField(choices=[(0, 'Plaćanje po uzeću.'), (1, 'Plaćanje preko uplatnice.')], default=0),
        ),
    ]
