# Generated by Django 3.0.1 on 2020-04-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('INT', 'Integer'), ('STR', 'String'), ('DEC', 'Decimal'), ('BOL', 'Bolean')], default='STR', max_length=3)),
                ('feature_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_feature_fea', to='product_category.Feature')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_feture_cat', to='product_category.SubCategory')),
            ],
        ),
    ]
